// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/twin-Instances": {
            "post": {
                "description": "This endpoint creates the Twin Instance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TwinInstances"
                ],
                "summary": "Create Twin Instance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TwinInstance"
                        }
                    }
                }
            }
        },
        "/twin-Instances/{instanceId}": {
            "delete": {
                "description": "This endpoint deletes the Twin Instance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TwinInstances"
                ],
                "summary": "Delete Twin Instance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TwinInstance"
                        }
                    }
                }
            }
        },
        "/twin-instances": {
            "get": {
                "description": "This endpoint returns all Twin Instances registered in the Platform.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TwinInstances"
                ],
                "summary": "Get All Twin Instances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.TwinInstance"
                            }
                        }
                    }
                }
            }
        },
        "/twin-instances/{instanceId}/{id}": {
            "get": {
                "description": "This endpoint returns the Twin Instance by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TwinInstances"
                ],
                "summary": "Get Twin Instance by Id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TwinInstance"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.TwinInstance": {
            "type": "object",
            "required": [
                "id",
                "interfaceId",
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interfaceId": {
                    "type": "string"
                },
                "lastEventData": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
