definitions:
  domain.TwinInstance:
    properties:
      active:
        type: boolean
      createdAt:
        type: string
      id:
        type: string
      interfaceId:
        type: string
      lastEventData:
        type: string
      name:
        type: string
      parent:
        type: string
    required:
    - id
    - interfaceId
    - name
    type: object
info:
  contact: {}
paths:
  /twin-Instances:
    post:
      consumes:
      - application/json
      description: This endpoint creates the Twin Instance.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TwinInstance'
      summary: Create Twin Instance
      tags:
      - TwinInstances
  /twin-Instances/{instanceId}:
    delete:
      consumes:
      - application/json
      description: This endpoint deletes the Twin Instance.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TwinInstance'
      summary: Delete Twin Instance
      tags:
      - TwinInstances
  /twin-instances:
    get:
      consumes:
      - application/json
      description: This endpoint returns all Twin Instances registered in the Platform.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.TwinInstance'
            type: array
      summary: Get All Twin Instances
      tags:
      - TwinInstances
  /twin-instances/{instanceId}/{id}:
    get:
      consumes:
      - application/json
      description: This endpoint returns the Twin Instance by id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TwinInstance'
      summary: Get Twin Instance by Id
      tags:
      - TwinInstances
swagger: "2.0"
